version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: securex-postgres
    environment:
      POSTGRES_USER: pushp
      POSTGRES_PASSWORD: securex_password
      POSTGRES_DB: securex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pushp -d securex_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: securex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: securex-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://pushp:securex_password@postgres:5432/securex_db?schema=public
      - JWT_SECRET=secx_master_production_jwt_secret_9841029481237912
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: securex-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres-data:
  redis-data:
